### ISSUE TITLE
feat: Statistics Section 구현

### ISSUE THREAD

**Issue by ShinHeeEul** [CoworkCode/coworking-space#10]
# Todo List
- [ ] Statistics 이미지 파일 추가
- [ ] 숫자 뒤 색 동그라미 추가
- [ ] Statistics Section 구현
- [ ] (선택) 숫자 올라가게 구현하기
