### ISSUE TITLE
docs: README.md 수정

### ISSUE THREAD

**Issue by ShinHeeEul** [CoworkCode/coworking-space#18]
# Todo List
- [x] 홈페이지 주소 첨부하기
- [x] 컨벤션 차트화 시키기
- [x] 프로젝트 설명 추가하기
